version: '3.8'

services:
  resto_go:
    build: .
    ports:
      - "8080:8080"
    command: ["/resto_go"]
    environment:
      DATABASE_URL: "postgres://romi:romi@db:5432/postgres"  # Cambiado de localhost a db
